# Generated by Django 4.2.26 on 2025-11-14 21:47

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('device_group', models.CharField(blank=True, max_length=255)),
                ('template', models.CharField(blank=True, max_length=255)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('external_integration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='panorama_connection', to='extras.externalintegration')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['external_integration__name'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PanoramaSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('sync_start', models.DateTimeField(auto_now_add=True)),
                ('sync_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('objects_created', models.IntegerField(default=0)),
                ('objects_updated', models.IntegerField(default=0)),
                ('objects_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='nautobot_panorama_ssot.panoramaconnection')),
            ],
            options={
                'verbose_name': 'Panorama Sync Log',
                'verbose_name_plural': 'Panorama Sync Logs',
                'ordering': ['-sync_start'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
