# Generated by Django 4.2.26 on 2025-11-16 03:47

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
        ('nautobot_panorama_ssot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOTPanoramaConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('device_group', models.CharField(blank=True, max_length=255)),
                ('template', models.CharField(blank=True, max_length=255)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('panorama_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panorama_connection', to='extras.externalintegration')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'SSOT Panorama Config',
                'verbose_name_plural': 'SSOT Panorama Configs',
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='panoramasynclog',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='nautobot_panorama_ssot.ssotpanoramaconfig'),
        ),
        migrations.DeleteModel(
            name='PanoramaConnection',
        ),
    ]
