# Generated by Django 4.2.26 on 2025-11-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
        ('nautobot_panorama_ssot', '0002_ssotpanoramaconfig_alter_panoramasynclog_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssotpanoramaconfig',
            name='panorama_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extras.externalintegration'),
        ),
    ]
