# Generated by Django 4.2.26 on 2025-11-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
        ('nautobot_panorama_ssot', '0003_alter_ssotpanoramaconfig_panorama_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssotpanoramaconfig',
            name='panorama_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panorama_instance', to='extras.externalintegration'),
        ),
    ]
