# Generated by Django 4.2.26 on 2025-11-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_panorama_ssot', '0004_alter_ssotpanoramaconfig_panorama_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssotpanoramaconfig',
            name='enable_sync_to_nautobot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ssotpanoramaconfig',
            name='job_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
